### ISSUE TITLE
Push and pull not working anymore in latest version

### ISSUE THREAD

**Issue by thijskaspers** [internetztube/craft-spreadsheet-translations#13]
After updating from 1.0 to 1.1.2 we are getting errors with pushing and pulling of the translations. Here are the stacktraces:

**push-missing-handles:**

````
Exception 'TypeError' with message 'Argument 1 passed to internetztube\spreadsheetTranslations\services\MissingHandleService::pushHandleToSpreadSheet() must be of the type string, array given, called in /var/www/vendor/internetztube/craft-spreadsheet-translations/src/console/controllers/MainController.php on line 46'

in /var/www/vendor/internetztube/craft-spreadsheet-translations/src/services/MissingHandleService.php:9

Stack trace:
#0 /var/www/vendor/internetztube/craft-spreadsheet-translations/src/console/controllers/MainController.php(46): internetztube\spreadsheetTranslations\services\MissingHandleService->pushHandleToSpreadSheet()
#1 [internal function]: internetztube\spreadsheetTranslations\console\controllers\MainController->actionPushMissingHandles()
#2 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#3 /var/www/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#4 /var/www/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction()
#5 /var/www/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction()
#6 /var/www/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction()
#7 /var/www/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction()
#8 /var/www/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction()
#9 /var/www/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest()
#10 /var/www/craft(22): yii\base\Application->run()
#11 {main}
````

**pull-translations:**

````
Exception 'ArgumentCountError' with message 'Too few arguments to function internetztube\spreadsheetTranslations\services\FetchService::rawRows(), 0 passed in /var/www/vendor/internetztube/craft-spreadsheet-translations/src/console/controllers/MainController.php on line 22 and at least 1 expected'

in /var/www/vendor/internetztube/craft-spreadsheet-translations/src/services/FetchService.php:69

Stack trace:
#0 /var/www/vendor/internetztube/craft-spreadsheet-translations/src/console/controllers/MainController.php(22): internetztube\spreadsheetTranslations\services\FetchService->rawRows()
#1 [internal function]: internetztube\spreadsheetTranslations\console\controllers\MainController->actionPullTranslations()
#2 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#3 /var/www/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#4 /var/www/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction()
#5 /var/www/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction()
#6 /var/www/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction()
#7 /var/www/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction()
#8 /var/www/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction()
#9 /var/www/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest()
#10 /var/www/craft(22): yii\base\Application->run()
#11 {main}
````

Note: The `push-missing-languages` command is still working properly.

**Comment by internetztube** [comment]
Sorry! Have unfortunately missed your issue. I' ll take a look at it this evening!

**Comment by thijskaspers** [comment]
No worries, we've downgraded for now. Thanks for looking into it!

**Comment by internetztube** [comment]
Thanks for your bug report. 
https://github.com/internetztube/craft-spreadsheet-translations/releases/tag/1.1.3
```
composer update internetztube/craft-spreadsheet-translations
```
